{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_django-{{ version }}.tar.gz
  sha256: 469c2d973619355645ec696bbc4afab836ce22cbc83236a0382c3090588f7772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.59b0
    - opentelemetry-instrumentation ==0.59b0
    - opentelemetry-semantic-conventions ==0.59b0
    - opentelemetry-util-http ==0.59b0
    - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.58b0
    # - opentelemetry-instrumentation-asgi ==0.59b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.django
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
