{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_django-{{ version }}.tar.gz
  sha256: 66efaf129f504e1958e9d20163a15051e49906a4c56acec359a8bc2503fd3300

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.42b0
    - opentelemetry-instrumentation ==0.42b0
    - opentelemetry-semantic-conventions ==0.42b0
    - opentelemetry-util-http ==0.42b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.37b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.38b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.39b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.40b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.41b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.42b0
    # - django >=1.10

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
