{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.35b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_django-{{ version }}.tar.gz
  sha256: 056d6f1700eed0b95b9a1df64a9dda372aa713085bb80ed4a009951969b9fec0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - hatchling
  run:
    - python >=3.7,<3.11
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.35b0
    - opentelemetry-instrumentation-wsgi ==0.35b0
    - opentelemetry-semantic-conventions ==0.35b0
    - opentelemetry-util-http ==0.35b0
    # - opentelemetry-test ==0.24b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-instrumentation-asgi ==0.26b1
    # - django >=1.10
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-instrumentation-asgi ==0.27b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-instrumentation-asgi ==0.28b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-instrumentation-asgi ==0.28b1
    # - django >=1.10
    # - opentelemetry-test-utils ==0.29b0
    # - opentelemetry-instrumentation-asgi ==0.29b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.30b0
    # - opentelemetry-instrumentation-asgi ==0.30b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.30b1
    # - opentelemetry-instrumentation-asgi ==0.30b1
    # - django >=1.10
    # - opentelemetry-test-utils ==0.31b0
    # - opentelemetry-instrumentation-asgi ==0.31b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.32b0
    # - opentelemetry-instrumentation-asgi ==0.32b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.33b0
    # - opentelemetry-instrumentation-asgi ==0.33b0
    # - django >=1.10

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
    - cshaley
