{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.56b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_django-{{ version }}.tar.gz
  sha256: 3ad1dff9b4c34d63fd5c512907ace38788bfbfa2d898353fb8c644925ed8a8b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.56b0
    - opentelemetry-instrumentation ==0.56b0
    - opentelemetry-semantic-conventions ==0.56b0
    - opentelemetry-util-http ==0.56b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.37b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.38b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.39b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.40b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.41b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.42b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.43b0
    # - django >=1.10
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-django 
    # - opentelemetry-instrumentation-asgi ==0.44b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.45b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.46b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.47b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.48b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.49b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.49b1
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.49b2
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.50b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.51b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.52b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.52b1
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.53b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.53b1
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.54b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.54b1
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.55b0
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.55b1
    # - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.56b0
    # - django >=1.10

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
