{% set name = "opentelemetry-instrumentation-django" %}
{% set version = "0.60b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_django-{{ version }}.tar.gz
  sha256: 765b69c7ccdea7e9ebfd0b9e68387956b8f74816f3e39775d5b06a20f16b0522

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.60b1
    - opentelemetry-instrumentation ==0.60b1
    - opentelemetry-semantic-conventions ==0.60b1
    - opentelemetry-util-http ==0.60b1
    - django >=1.10
    # - opentelemetry-instrumentation-asgi ==0.58b0
    # - opentelemetry-instrumentation-asgi ==0.59b0
    # - opentelemetry-instrumentation-asgi ==0.60b0
    # - opentelemetry-instrumentation-asgi ==0.60b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.django
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-django
  summary: OpenTelemetry Instrumentation for Django
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
